// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: testing.sql

package database

import (
	"context"
)

const deleteRows = `-- name: DeleteRows :exec
DELETE FROM users
`

func (q *Queries) DeleteRows(ctx context.Context) error {
	_, err := q.db.ExecContext(ctx, deleteRows)
	return err
}
